name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install deps
        working-directory: client
        run: npm ci

      - name: Create .env.production for Vite
        working-directory: client
        run: |
          echo "VITE_API_URL=https://food-delivery-webbsite-production.up.railway.app" > .env.production

      - name: Build
        working-directory: client
        run: npm run build

      - name: Copy index to 404
        run: cp client/dist/index.html client/dist/404.html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: client/dist
          publish_branch: github-pages
          force_orphan: true
